export const books = [
  {
    "name": "设计数据密集型应用",
    "originalName": "Designing Data-Intensive Applications",
    "category": "技术",
    "startAt": "2024/05",
    "endAt": "2024/06",
    "rate": 5,
    "comments": "近几年读过最好的技术书，看着书名不知所以，看完以后发现没有比这更合适的名字了。对于后端开发很有启发，深入浅出的讲解了从数据编码、到数据库、分布式系统各个维度的内容，十分推荐",
    "data": {
      "abstract": "Martin Kleppmann / 赵军平 / 李三平 / 吕云松 / 耿煜 / 中国电力出版社 / 2018-9-1 / 128",
      "abstract_2": "",
      "cover_url": "https://img1.doubanio.com/view/subject/m/public/s34186559.jpg",
      "extra_actions": [],
      "id": 30329536,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'30329536',query:'%E8%AE%BE%E8%AE%A1%E6%95%B0%E6%8D%AE%E5%AF%86%E9%9B%86%E5%9E%8B%E5%BA%94%E7%94%A8',i:'1',cat_id:'1001'})\"",
      "rating": {
        "count": 1770,
        "rating_info": "",
        "star_count": 5,
        "value": 9.6
      },
      "title": "数据密集型应用系统设计",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/30329536/",
      "titleMatchScore": 1,
      "itemRating": 1770
    },
    "author": "Martin Kleppmann"
  },
  {
    "name": "架构师修炼之道",
    "originalName": "The Software Architect Elevator",
    "category": "技术",
    "startAt": "2024/06",
    "endAt": "2024/07",
    "rate": 3,
    "comments": "工具书非技术书，作为架构师需要怎么规划、管理项目，可以使用哪些工具、方法论等，对于我实用度一般",
    "data": {
      "abstract": "[美] Michael Keeling / 马永辉 / 顾昕 / 华中科技大学出版社 / 2019-8-1 / 99.90元",
      "abstract_2": "",
      "cover_url": "https://img1.doubanio.com/view/subject/m/public/s33458550.jpg",
      "extra_actions": [],
      "id": 34795642,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'34795642',query:'%E6%9E%B6%E6%9E%84%E5%B8%88%E4%BF%AE%E7%82%BC%E4%B9%8B%E9%81%93',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 99,
        "rating_info": "",
        "star_count": 4,
        "value": 7.6
      },
      "title": "架构师修炼之道",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/34795642/",
      "titleMatchScore": 1,
      "itemRating": 99
    },
    "author": "Michael Keeling"
  },
  {
    "name": "八次危机",
    "category": "人文",
    "startAt": "2024/07",
    "rate": 5,
    "comments": "之前B站上看到过温老师的视频，被吸引过来，书中干货很多，关于农村、中国经济的一些观点独到，和以前学到的历史很有大差异",
    "data": {
      "abstract": "温铁军 等 / 东方出版社 / 2013-1-1 / 55.00元",
      "abstract_2": "",
      "cover_url": "https://img1.doubanio.com/view/subject/m/public/s26862050.jpg",
      "extra_actions": [],
      "id": 20394150,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'20394150',query:'%E5%85%AB%E6%AC%A1%E5%8D%B1%E6%9C%BA',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 8909,
        "rating_info": "",
        "star_count": 4.5,
        "value": 8.9
      },
      "title": "八次危机 : 中国的真实经验",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/20394150/",
      "titleMatchScore": 1,
      "itemRating": 8909
    },
    "author": "温铁军"
  },
  {
    "name": "晚清的最后十八年",
    "category": "人文",
    "startAt": "2024/07",
    "rate": 4,
    "comments": "又名清朝末年哪些事儿，看起来非常流畅，好像作者参与了整个事件一样，就是有时候某些抒情和心里描写略显中二",
    "data": {
      "abstract": "黄治军 / 花城出版社 / 2016-1 / 42.00",
      "abstract_2": "",
      "cover_url": "https://img3.doubanio.com/view/subject/m/public/s28369083.jpg",
      "extra_actions": [],
      "id": 26694140,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'26694140',query:'%E6%99%9A%E6%B8%85%E7%9A%84%E6%9C%80%E5%90%8E%E5%8D%81%E5%85%AB%E5%B9%B4',i:'1',cat_id:'1001'})\"",
      "rating": {
        "count": 1242,
        "rating_info": "",
        "star_count": 4,
        "value": 7.6
      },
      "title": "晚清最后十八年 : 从甲午战争到辛亥革命",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/26694140/",
      "titleMatchScore": 0.875,
      "itemRating": 1242
    },
    "author": "黄治军"
  },
  {
    "name": "幸得诸君慰平生",
    "category": "人文",
    "startAt": "2024/03",
    "endAt": "2024/03",
    "rate": 3,
    "comments": "中篇《金钱珍》看起来很有意思，生活琐事有点无趣，一些散文的描写能觉察出作者是个很细腻很会观察生活的人",
    "data": {
      "abstract": "故园风雨前 / 杨云苏 / 清华大学出版社 / 2017-12-1 / 55.00",
      "abstract_2": "",
      "cover_url": "https://img3.doubanio.com/view/subject/m/public/s33494922.jpg",
      "extra_actions": [],
      "id": 27623390,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'27623390',query:'%E5%B9%B8%E5%BE%97%E8%AF%B8%E5%90%9B%E6%85%B0%E5%B9%B3%E7%94%9F',i:'1',cat_id:'1001'})\"",
      "rating": {
        "count": 3354,
        "rating_info": "",
        "star_count": 4.5,
        "value": 8.6
      },
      "title": "幸得诸君慰平生",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/27623390/",
      "titleMatchScore": 1,
      "itemRating": 3354
    },
    "author": "故园风雨前"
  },
  {
    "name": "Release It! Design and Deploy Production-ready Software",
    "category": "技术",
    "startAt": "2024/06",
    "endAt": "",
    "rate": 4,
    "comments": "英文看起来有些吃力，进行中",
    "data": {
      "abstract": "Michael T. Nygard / Pragmatic Bookshelf / 2007-03-30 / USD 34.95",
      "abstract_2": "",
      "cover_url": "https://img9.doubanio.com/view/subject/m/public/s4280015.jpg",
      "extra_actions": [],
      "id": 2065284,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'2065284',query:'Release%20It%21%20Design%20and%20Deploy%20Production-ready%20Software',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 48,
        "rating_info": "",
        "star_count": 4,
        "value": 8.4
      },
      "title": "Release It! : Design and Deploy Production-Ready Software (Pragmatic Programme",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/2065284/",
      "titleMatchScore": 1,
      "itemRating": 48
    },
    "author": "Michael T. Nygard"
  },
  {
    "name": "置身事内",
    "category": "人文",
    "startAt": "2023/08",
    "endAt": "2024/12",
    "rate": 5,
    "comments": "深入理解中国的政府是怎么运作的，受益匪浅",
    "data": {
      "abstract": "兰小欢 / 上海人民出版社 / 2021-8 / 65.00元",
      "abstract_2": "",
      "cover_url": "https://img3.doubanio.com/view/subject/m/public/s33956867.jpg",
      "extra_actions": [],
      "id": 35546622,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'35546622',query:'%E7%BD%AE%E8%BA%AB%E4%BA%8B%E5%86%85',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 81669,
        "rating_info": "",
        "star_count": 4.5,
        "value": 9.1
      },
      "title": "置身事内 : 中国政府与经济发展",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/35546622/",
      "titleMatchScore": 1,
      "itemRating": 81669
    },
    "author": "兰小欢"
  },
  {
    "name": "穷爸爸与富爸爸",
    "category": "人文",
    "startAt": "2023/10",
    "endAt": "2023/11",
    "rate": 4,
    "comments": "理财入门书，对于财务自由的一些观点很有启发",
    "data": {
      "abstract": "（美）罗伯特・T・清崎 / 莎伦・L・莱希特 / 杨君 / 杨明 / 世界图书出版公司 / 2000-09 / 18.80",
      "abstract_2": "",
      "cover_url": "https://img1.doubanio.com/view/subject/m/public/s11229869.jpg",
      "extra_actions": [],
      "id": 1033778,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'1033778',query:'%E7%A9%B7%E7%88%B8%E7%88%B8%E4%B8%8E%E5%AF%8C%E7%88%B8%E7%88%B8',i:'2',cat_id:'1001'})\"",
      "rating": {
        "count": 78003,
        "rating_info": "",
        "star_count": 4,
        "value": 8.3
      },
      "title": "富爸爸，穷爸爸",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/1033778/",
      "titleMatchScore": 0.75,
      "itemRating": 78003
    },
    "author": "罗伯特・T・清崎"
  },
  {
    "name": "欧亨利短篇小说集",
    "category": "人文",
    "startAt": "2024/05",
    "endAt": "2024/05",
    "rate": 3.5,
    "comments": "初看很有意思，看多了都是一样的套路",
    "data": {
      "abstract": "欧·亨利 / 牛振华 / 上海三联书店 / 2010-1 / 32.00元",
      "abstract_2": "",
      "cover_url": "https://img2.doubanio.com/view/subject/m/public/s6110791.jpg",
      "extra_actions": [],
      "id": 4215931,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'4215931',query:'%E6%AC%A7%E4%BA%A8%E5%88%A9%E7%9F%AD%E7%AF%87%E5%B0%8F%E8%AF%B4%E9%9B%86',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 887,
        "rating_info": "",
        "star_count": 4.5,
        "value": 8.8
      },
      "title": "欧·亨利短篇小说集",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/4215931/",
      "titleMatchScore": 1,
      "itemRating": 887
    },
    "author": "欧·亨利"
  },
  {
    "name": "局外人",
    "category": "人文",
    "startAt": "2024/04",
    "endAt": "2024/04",
    "rate": 3.5,
    "comments": "小说很短，但确实也没太看懂想表达什么",
    "data": {
      "abstract": "[法] 阿尔贝·加缪 / 柳鸣九 / 上海译文出版社 / 2010-8 / 22.00元",
      "abstract_2": "",
      "cover_url": "https://img9.doubanio.com/view/subject/m/public/s4468484.jpg",
      "extra_actions": [],
      "id": 4908885,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'4908885',query:'%E5%B1%80%E5%A4%96%E4%BA%BA',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 242048,
        "rating_info": "",
        "star_count": 4.5,
        "value": 9.1
      },
      "title": "局外人",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/4908885/",
      "titleMatchScore": 1,
      "itemRating": 242048
    },
    "author": "阿尔贝·加缪"
  },
  {
    "name": "凤凰架构",
    "category": "技术",
    "startAt": "2023/06",
    "endAt": "2023/12",
    "rate": 5,
    "comments": "结合例子讲解了软件架构的演进，几乎涵盖了分布式系统的各个方面，时不时遇到对应的问题翻一翻",
    "data": {
      "abstract": "周志明 / 机械工业出版社 / 2021-6-30 / 99.00",
      "abstract_2": "",
      "cover_url": "https://img3.doubanio.com/view/subject/m/public/s33966407.jpg",
      "extra_actions": [],
      "id": 35492898,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'35492898',query:'%E5%87%A4%E5%87%B0%E6%9E%B6%E6%9E%84',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 685,
        "rating_info": "",
        "star_count": 4.5,
        "value": 9.2
      },
      "title": "凤凰架构 : 构建可靠的大型分布式系统",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/35492898/",
      "titleMatchScore": 1,
      "itemRating": 685
    },
    "author": "周志明"
  },
  {
    "name": "窗边的小豆豆",
    "category": "人文",
    "startAt": "2024/09",
    "endAt": "2024/09",
    "rate": 4,
    "comments": "哪里有真实的巴学园，能容纳孩子的天真",
    "data": {
      "abstract": "[日] 黑柳彻子 著 / 岩崎千弘 图 / 赵玉皎 / 南海出版公司 / 2003-1 / 20.00元",
      "abstract_2": "",
      "cover_url": "https://img2.doubanio.com/view/subject/m/public/s1067911.jpg",
      "extra_actions": [],
      "id": 1007914,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'1007914',query:'%E7%AA%97%E8%BE%B9%E7%9A%84%E5%B0%8F%E8%B1%86%E8%B1%86',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 214548,
        "rating_info": "",
        "star_count": 4.5,
        "value": 8.8
      },
      "title": "窗边的小豆豆",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/1007914/",
      "titleMatchScore": 1,
      "itemRating": 214548
    },
    "author": "黑柳彻子"
  },
  {
    "name": "世上为什么要有图书馆",
    "category": "人文",
    "startAt": "2024/09",
    "endAt": "2024/09",
    "rate": 4.5,
    "comments": "按照作者的话说这是一部芝麻官札记，站在一个局长的角度描述很有意思。唯一不足是后半部分写了很多看书荐书的人，太过散了",
    "data": {
      "abstract": "杨素秋 / 上海译文出版社 / 2024-1-1 / 58.00元",
      "abstract_2": "",
      "cover_url": "https://img9.doubanio.com/view/subject/m/public/s34705784.jpg",
      "extra_actions": [],
      "id": 36593622,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'36593622',query:'%E4%B8%96%E4%B8%8A%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E6%9C%89%E5%9B%BE%E4%B9%A6%E9%A6%86',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 12142,
        "rating_info": "",
        "star_count": 4.5,
        "value": 9
      },
      "title": "世上为什么要有图书馆",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/36593622/",
      "titleMatchScore": 1,
      "itemRating": 12142
    },
    "author": "杨素秋"
  },
  {
    "name": "病榻杂记",
    "category": "人文",
    "startAt": "2024/09",
    "endAt": "2024/09",
    "rate": 4,
    "comments": "九十多岁的老头还能这么真诚的写作，能与时俱进的谈到当前各种社会问题，能客观的评价自己，太难得了。印象最深是写老年十忌的文章",
    "data": {
      "abstract": "季羡林 / 新世界出版社 / 2007 / 29.80元",
      "abstract_2": "",
      "cover_url": "https://img1.doubanio.com/view/subject/m/public/s1987130.jpg",
      "extra_actions": [],
      "id": 1958771,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'1958771',query:'%E7%97%85%E6%A6%BB%E6%9D%82%E8%AE%B0',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 633,
        "rating_info": "",
        "star_count": 3.5,
        "value": 7.4
      },
      "title": "病榻杂记",
      "topics": [],
      "tpl_name": "search_subject",
      "url": "https://book.douban.com/subject/1958771/",
      "titleMatchScore": 1,
      "itemRating": 633
    },
    "author": "季羡林"
  }
];